easy_admin:
    entities:
        # List the entity class name you want to manage
        - App\Entity\Contract
        - App\Entity\ContractProduct
        - App\Entity\Counterparty
        - App\Entity\Orders
        - App\Entity\OrdersProduct
        - App\Entity\Product
        - App\Entity\User
